- src/SchedulePolicy/DeadlinePolicy.php
- src/SchedulePolicy/SchedulePolicyOrchestrator.php
- tests/SchedulePolicy/DeadlinePolicyTest.php
- tests/SchedulePolicy/SchedulePolicyOrchestratorTest.php
> refactor(schedulepolicy): DeadlinePolicy improvements

- src/Bridge/Doctrine/Transport/Connection.php
- tests/Bridge/Doctrine/Transport/ConnectionTest.php
- tests/Bridge/Doctrine/Transport/DoctrineTransportTest.php
> refactor(bridge): Doctrine extra log removed

- src/DependencyInjection/SchedulerBundleExtension.php
- tests/DependencyInjection/SchedulerBundleExtensionTest.php
| Bundle version?  | 0.4.2
| Symfony version? | 5.6.2
| Discussion?      | #82
> fix(dic): config:dump-reference

- CHANGELOG.md
> changelog(0.4.3): tagged

- composer.json
- src/Bridge/Doctrine/Transport/Connection.php
- src/Task/TaskListInterface.php
- tests/Bridge/Doctrine/Transport/ConnectionIntegrationTest.php
- tests/Transport/FilesystemTransportTest.php
> refactor(bridge): Doctrine extra sort removed

- .symfony.insight.yaml
- rector.php
- src/Bridge/Doctrine/SchemaListener/SchedulerTransportDoctrineSchemaSubscriber.php
- src/Bridge/Doctrine/Transport/Connection.php
- src/Command/ConsumeTasksCommand.php
- src/Expression/ExpressionBuilder.php
- src/Transport/Configuration/FailOverConfiguration.php
- src/Transport/FailOverTransport.php
- src/Transport/LongTailTransport.php
- src/Transport/RoundRobinTransport.php
- src/Worker/Worker.php
- tests/Worker/WorkerTest.php
> refactor(worker): locked task middleware run

- README.md
Preview: https://github.com/jmsche/SchedulerBundle/blob/772f82e3a2da32d8dfaf6f17f1fc6f64470902f9/README.md
> Fix badges on README (following daily workflow removal)

- CHANGELOG.md
> changelog(0.4.4): tagged

- doc/command.md
- src/Command/ConsumeTasksCommand.php
- src/Scheduler.php
- tests/Command/ConsumeTasksCommandTest.php
- tests/SchedulerTest.php
> refactor(scheduler): improvements on executed tasks

- CHANGELOG.md
> changelog(0.4.5): tagged

- src/Scheduler.php
> refactor(scheduler): due tasks filter fixed

- CHANGELOG.md
> changelog(0.4.7): tagged

- src/Scheduler.php
- tests/SchedulerTest.php
> refactor(scheduler): fix on last_execution usage

- README.md
> fix(readme): extra rector removed

- CHANGELOG.md
> changelog(0.4.8): tagged

- CHANGELOG.md
> changelog(0.4.9): tagged

- README.md
- doc/best_practices.md
- doc/events.md
- doc/worker.md
- src/Event/WorkerForkedEvent.php
- src/EventListener/WorkerLifecycleSubscriber.php
- src/Runner/ChainedTaskRunner.php
- src/Task/ProbeTask.php
- src/Worker/AbstractWorker.php
- src/Worker/WorkerInterface.php
- tests/Event/WorkerForkedEventTest.php
- tests/EventListener/WorkerLifecycleSubscriberTest.php
- tests/Runner/ChainedTaskRunnerTest.php
- tests/Worker/WorkerTest.php
> refactor(worker): fork improved

- composer.json
- phpstan.neon.dist
- tests/EventListener/ProbeStateSubscriberTest.php
- tests/EventListener/TaskSubscriberTest.php
> tools(phpstan): deprecation rules added

- src/Command/ListFailedTasksCommand.php
- src/Command/ListTasksCommand.php
- src/Task/LazyTaskList.php
- src/Task/TaskList.php
- src/Task/TaskListInterface.php
- tests/Command/ListFailedTasksCommandTest.php
- tests/Command/ListTasksCommandTest.php
- tests/Task/LazyTaskListTest.php
- tests/Task/TaskListTest.php
| Bundle version?  | -
| New feature?     | yes (improvement)
| Discussion?      | #87
Display related substasks and type task in `scheduler:list`command.
output: 
```bash 
[OK] 3 tasks found
+-------------+---------+------------------------+------------+---------------------------+---------------------------+-------------------------+-----------------------------+---------+------+
| Type        | Name    | Description            | Expression | Last execution date       | Next execution date       | Last execution duration | Last execution memory usage | State   | Tags |
+-------------+---------+------------------------+------------+---------------------------+---------------------------+------ …
```
> feat(command): ListTaskCommand - display substasks

- CHANGELOG.md
| Bundle version?  | 0.5.0
| New feature?     | yes
> changelog(0.5.0): tagged

- src/Transport/FilesystemTransportFactory.php
- tests/Transport/FilesystemTransportFactoryTest.php
> refactor(transport): FilesystemTransportFactory improved

- src/Command/ConsumeTasksCommand.php
- tests/Command/ConsumeTasksCommandTest.php
| Bundle version?  | 0.5.4
Since `0.4.5`, the `wait` option does not behave as expected as the tasks are not executed if each task is paused, this way, the worker never try to wait for the next tasks to execute.
The command should supply an option that allow to force this behaviour.
Opened with @Bastien2805
> feat(command): --force option added to scheduler:consume

- src/Bridge/Doctrine/Transport/Connection.php
- tests/Bridge/Doctrine/Transport/ConnectionIntegrationTest.php
> refactor(bridge): Doctrine connection improved

- doc/command.md
- doc/scheduler.md
- src/Command/ConsumeTasksCommand.php
- src/EventListener/TaskLifecycleSubscriber.php
- src/LazyScheduler.php
- src/Scheduler.php
- src/SchedulerInterface.php
- src/Task/AbstractTask.php
- src/Task/TaskInterface.php
- src/Worker/AbstractWorker.php
- src/Worker/WorkerConfiguration.php
- tests/Command/ConsumeTasksCommandTest.php
- tests/EventListener/TaskLifecycleSubscriberTest.php
- tests/SchedulerTest.php
- tests/Worker/WorkerConfigurationTest.php
- tests/Worker/WorkerTest.php
| Bundle version?  | 0.6.2
| Symfony version? | >= 5.2
> refactor(scheduler): strict mode

- src/EventListener/StopWorkerOnSignalSubscriber.php
- src/Task/TaskInterface.php
- src/Worker/AbstractWorker.php
- tests/Runner/CommandTaskRunnerTest.php
- tests/Worker/WorkerTest.php
| Bundle version?  | 0.7.0
| Symfony version? | >= 5.2
> refactor(worker): improvements on stop

- .cloud/docker/Dockerfile
- .dockerignore
- .github/CONTRIBUTING.md
- Makefile
- docker-compose.yaml
| Bundle version?  | 0.8.0
| Symfony version? | >= 5.2
> build(docker): configuration started

- src/Transport/AbstractCompoundTransport.php
- src/Transport/FailOverTransport.php
- src/Transport/FailOverTransportFactory.php
- src/Transport/LongTailTransport.php
- src/Transport/LongTailTransportFactory.php
- src/Transport/RoundRobinTransport.php
- src/Transport/RoundRobinTransportFactory.php
- src/Transport/TransportRegistry.php
- src/Transport/TransportRegistryInterface.php
- tests/Transport/FailOverTransportTest.php
- tests/Transport/LongTailTransportTest.php
- tests/Transport/RoundRobinTransportTest.php
- tests/Worker/WorkerTest.php
| Bundle version?  | 0.8.0
| Symfony version? | > 5.4
| New feature?     | yes
> feat(transport): Registry introduced

- .gitignore
- Makefile
- docker-compose.override.yaml.dist
- src/Scheduler.php
| PHP version?     | 8.0
| Bundle version?  | 0.8.1
| Discussion?      | #216
> refactor(scheduler): float check improved

- .github/workflows/code-style.yml
- .github/workflows/infection.yml
- .github/workflows/phpunit.yml
- .github/workflows/rector.yml
- .github/workflows/security.yml
- .github/workflows/static-analysis.yml
| PHP version?     | <= 8.2
| Bundle version?  | >= 0.9.0
> ci(php): 8.2 support started

- src/DependencyInjection/SchedulerBundleExtension.php
- src/Fiber/AbstractFiberHandler.php
- src/FiberScheduler.php
- src/Transport/Configuration/FiberConfiguration.php
- src/Transport/FiberTransport.php
- src/Transport/FiberTransportFactory.php
- src/Transport/TransportInterface.php
- src/Worker/ExecutionPolicy/FiberPolicy.php
- tests/DependencyInjection/SchedulerBundleExtensionTest.php
- tests/Transport/FiberTransportFactoryTest.php
| PHP version?     | 8.0
| Bundle version?  | 0.9.0
> refactor(core): Fibers improvement

- src/DependencyInjection/SchedulerBundleExtension.php
- src/Middleware/SingleRunTaskMiddleware.php
- src/Middleware/TaskUpdateMiddleware.php
- tests/Command/DebugMiddlewareCommandTest.php
- tests/DependencyInjection/SchedulerBundleExtensionTest.php
- tests/FiberSchedulerTest.php
- tests/LazySchedulerTest.php
- tests/Middleware/SingleRunTaskMiddlewareTest.php
- tests/Middleware/TaskUpdateMiddlewareTest.php
- tests/SchedulerTest.php
- tests/Worker/FiberWorkerTest.php
- tests/Worker/WorkerTest.php
| PHP version?     | 8.0
| Bundle version?  | 0.9.1
> fix(dic): extra scheduler injection removed

- composer.json
> build(rector): version fixed

- tests/Serializer/AccessLockBagNormalizerTest.php
- tests/Task/LazyTaskListTest.php
- tests/Task/MessengerTaskTest.php
- tests/Transport/RoundRobinTransportTest.php
> fix(tests): improvements

- .cloud/docker/Dockerfile
- .github/workflows/docker.yml
| Bundle version?  | 0.9.4
| Bug fix?         | yes? (CI fix)
Docker workflow fails apparently because versions are not pinned; let's give it a try
> Attempt to fix docker workflow

- .gitattributes
| Bundle version?  | 0.9.3
Hi there,
This PR improves the .gitattributes by removing almost everything except the src directory & composer.json file from the package composer downloads.
Tell me if I should re-add some files/directories (README, LICENSE, doc?)
> Improve .gitattributes

- README.md
> doc(readme): remove $ so copy to clipboard works

- src/Command/ConsumeTasksCommand.php
- src/Command/DebugConfigurationCommand.php
- src/Command/DebugMiddlewareCommand.php
- src/Command/DebugProbeCommand.php
- src/Command/ExecuteExternalProbeCommand.php
- src/Command/ExecuteTaskCommand.php
- src/Command/ListFailedTasksCommand.php
- src/Command/ListTasksCommand.php
- src/Command/RebootSchedulerCommand.php
- src/Command/RemoveFailedTaskCommand.php
- src/Command/RetryFailedTaskCommand.php
- src/Command/YieldTaskCommand.php
> refactor(command): attribute introduced

- rector.php
- src/Scheduler.php
- src/Task/TaskList.php
- src/Transport/AbstractTransport.php
- src/Transport/InMemoryTransport.php
- tests/AbstractSchedulerTestCase.php
- tests/Bridge/Doctrine/Transport/ConnectionIntegrationTest.php
- tests/FiberSchedulerTest.php
- tests/LazySchedulerTest.php
- tests/SchedulerTest.php
- tests/Task/TaskListTest.php
> refactor(core): Scheduler scheduling phase improved

- composer.json
| Bundle version?  | current
Should fix most workflows
> Fix composer plugin issue

- doc/command.md
- src/Scheduler.php
- tests/Transport/FailOverTransportTest.php
> refactor(scheduler): reboot handling

- CHANGELOG.md
> build(changelog): 0.10.0 tagged

- composer.json
- tests/Serializer/TaskNormalizerTest.php
- tests/Task/HttpTaskTest.php
- tests/Task/ShellTaskTest.php
| Bundle version?  | 0.10.1
| New feature?     | yno
> build(deps): deps improved

- CHANGELOG.md
> build(changelog): 0.10.1 tagged

- README.md
| Bundle version?  | N/A
CI badges on README are currently failing, see https://github.com/badges/shields/issues/8671 for the reason
> doc(readme): CI badges fixed

- CHANGELOG.md
> build(changelog): 0.10.2 tagged

- composer.json
| Bundle version?  | 0.10.2
| Bug fix?         | yes?
This PR should fix the security workflow
> Fix the security workflow: symfony/http-kernel

- src/Serializer/AccessLockBagNormalizer.php
- src/Serializer/NotificationTaskBagNormalizer.php
- src/Serializer/SchedulerConfigurationNormalizer.php
- src/Serializer/TaskNormalizer.php
| PHP version?     | 8.2
| Bundle version?  | 0.10.2
| Symfony version? | 6.3.0
| Bug fix?         | yes?
| Discussion?      | #315 
This PR should fix the deprecations coming with Symfony 6.3 (see #315).
> Fix Symfony 6.3 deprecation

- .cloud/docker/Dockerfile
- .github/workflows/docker.yml
| Bundle version?  | 0.10.2
Try to fix the Docker workflow by upgrading the hadolint action
> Try to fix Docker workflow

- CHANGELOG.md
> build(changelog): 0.10.3 tagged

- CHANGELOG.md
> build(changelog): 0.10.4 tagged
